### ISSUE TITLE
Tracking issue: feedback from building bundle size viewer

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#1456]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Collecting some feedback while building a bundle size viewer that's based on function datasource

### function: 
- [ ] https://github.com/mui/mui-toolpad/issues/1452
- [ ] https://github.com/mui/mui-toolpad/issues/1453
- [ ] https://github.com/mui/mui-toolpad/issues/1324
- [x] https://github.com/mui/mui-toolpad/pull/1454
- [ ] `fetch` could support caching of REST reponses serverside to reduce overfetching
### DataGrid:
- [ ] https://github.com/mui/mui-toolpad/issues/137
- [ ] It's not possible to create a DataGrid that fills the height of the viewport and scrolls within
- [x] https://github.com/mui/mui-toolpad/issues/649
- [x] Columns should allow formatting (pretty printing of bytes, units, currency) https://github.com/mui/mui-toolpad/pull/1449
- [ ] DataGrid columns can be reordered in the canvas, which persists in the Toolpad datamodel, but it should also be possible in DataGrid Column editor through drag and drop
### General:
- [ ] hierarchy explorer should be more like vscode:
  - [ ] Allow renaming inline
  - [ ] Allow reordering

### Feedback

1. How can we encourage users to move as much of dataprocessing serverside.
2. The function query editor is very information dense and all the options around are distracting while authoring the code. In pro-code I usually have only 1 code editor open at the same time, and achieve better focus. Easier to resize/position to my needs.
