### ISSUE TITLE
Getting started with Toolpad to be improved

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1653]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

- [x] add `--help` command to CLI (move to `yargs`?) https://github.com/mui/mui-toolpad/issues/1744
- [x]  `toolpad init `command? For quick setup (or something like create-toolpad-app)
- [x]  automatically pick another port if 3000 is in use, only in dev mode, when no port has been specified
- [x]  automatically open the browser on start i.e, user will not have to click, only in dev mode, with an opt-out cli argument
- [x]  avoid having to install `@mui/toolpad-core`. https://github.com/mui/mui-toolpad/pull/1793. Can we have users import e.g. `createComponent` from `@mui/toolpad`?
    - something like: `import { createComponent } from '@mui/toolpad/client'`
    - `import { createQuery } from '@mui/toolpad/server'`

**Comment by Janpot** [comment]
We are currently using `get-port` in the tests. `execa` in the CLI, `arg` for CLI argument parsing, and `chalk` is used in some of the dev scripts
