### ISSUE TITLE
DX checklist for Toolpad

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1669]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Improve DX for developing on toolpad locally: 

- [x] default files. https://github.com/mui/mui-toolpad/issues/1653
- [x] View DOM doesn't work
- [x] In query editor, `Open editor` button doesn't work: added https://github.com/mui/mui-toolpad/issues/1689 for improvements

https://user-images.githubusercontent.com/92228082/219275667-9d63fc2f-84ba-4a08-937c-c05773871461.mov

**Comment by Janpot** [comment]
@prakhargupta1 View DOM works for me. Has this been fixed in the meantime? If not, could you provide an exact reproduction?

**Comment by prakhargupta1** [comment]
It is working now.
