### ISSUE TITLE
Batch of issues

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#257]
Batch of issues that came up while building https://master--toolpad.mui.com/api/deploy/cl1md1cyq0002a0q0yemh2mdq/cl1md6lsr00023e6847l82lhc

Some of these will need to be broken out into their own issues or postponed

- [x] While creating the Typography components, intuitively was looking for a copy+paste workflow as these three elements are almost identical except for some small tweaks. https://github.com/mui/mui-toolpad/issues/413
- [x] Api update button is annoying, I always forget to click it, let's either block page navigation if it's unsaved, or use immediate input, similar to how the "name" textfields work, or component properties
- [x] How do you preview your api result when you add params but no default values
- [x] When binding on a Typography breaks (e.g. after renaming the source element) the text becomes unselectable. There's 3 issues here
  - [x] renaming an element should result in updating all expressions bound to it https://github.com/mui/mui-toolpad/issues/94
  - [x] a Text component shouldn't disappear when empty
  - [x] we need a way to visualize app hierarchy and select components https://github.com/mui/mui-toolpad/issues/490
- [x] page title should be adjustable and not be "Toolpad sandbox"
- [x] Option to wrap the whole page in a `Container` element https://github.com/mui/mui-toolpad/issues/492
- [x] `Select` provide a minimum width
- [x] `Select` visual values editor (like DataGrid columns) instead of JSON editor
- [x] individual "release" page, no way to navigate to "releases" or editor"
- [x] typo in release description, no way to update https://github.com/mui/mui-toolpad/issues/493
- [x] flash of "Not deployed yet..." during loading of application pages overview
- [x] release/deploy urls, rewrite to remove `/api` prefixes
- [x] release assets: add cache headers
- [x] editor empty state, show list of pages
- [x] app description on home overview, either remove the dummy description or add ability => replaced by createdAt date

Some comments from last team meeting as well:

- [x] Controlled prop to controlled prop binding (e.g. bind two textfields together)
- [x] Improve binding editor to be more self-documenting
- [x] Perhaps add some binding editor specific docs
- [x] Page code file that allows importing ESM and have exported bindings available as globals in page binding editor https://github.com/mui/mui-toolpad/issues/314
- [x] detect and parse CSV on REST APIs (and perhaps other content-types) https://github.com/mui/mui-toolpad/issues/494
- [x] API transform response before sending to browser (We can do this now that we can run javascript on the server)

After building https://master--toolpad.mui.com/deploy/cl27ajqfu0403a0oz236ay3pj/pages/cl27arb1i00043g693pzhex2r

- [x] pass options to `react-query`, for instance, in this case we might want to avoid refetching when the page opens.
       `refetchOnWindowFocus`, `refetchOnReconnect` and `refetchInterval`
- [x] need a way to refresh a queryState by button click

**Comment by Janpot** [comment]
Went through the list and created separate issues for the larger or less urgent tasks
