### ISSUE TITLE
Frustrations found along the way of building the dog app

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#309]
The app: https://master--toolpad.mui.com/_toolpad/app/cl1c2j0l512939zo6a43575en/editor/pages/cl27gc98v00003f69ideijta5
I have prefixed each of the pain points under two different categories: UX vs. DX

- UX (7): a generic notion, this is the kind of challenge that you would face working on a generic product, like Airbnb.
- DX (6): similar to UX, but you would need to imagine yourself as a developer to resonate with the usability pain.

My notes:

- [x] DX: Having to create a connection to make a fetch call seems a bit overkill. I get the use cases to be able to create REST connections, e.g. to add basic auth headers or to differentiate between the staging and production environment. Maybe it would make sense to have a generic REST connection that would always be available for usage. So that it's only once you face a specific need that you use it. It would have saved me one action. https://github.com/mui/mui-toolpad/issues/364

<img width="447" alt="Screenshot 2022-04-22 at 00 06 24" src="https://user-images.githubusercontent.com/3165635/164559477-9a9c44d6-93e3-4204-a672-dd386dcc5111.png">

- [x] UX: I have created an API and left the view but now I'm confused. My URL is not persisted? I need to click on the UPDATE button. The challenge is that we don't want to auto-save mistakes in the URL. I would suggest we have a dialog to confirm abandoning the changes when trying to leave. It will help build muscle and learn to save the changes. This caught me **multiple** times, it's painful.

<img width="332" alt="Screenshot 2022-04-22 at 00 06 45" src="https://user-images.githubusercontent.com/3165635/164559554-6d899818-67a3-405a-9609-a555e40e1f1a.png">

- [x] DX: Would it be possible to apply post transformations on my query states? I get that I can apply this transformation when I bind the value to a prop or a component, but I feel that I could save one context shifting. https://github.com/mui/mui-toolpad/issues/366

<img width="732" alt="Screenshot 2022-04-22 at 00 07 12" src="https://user-images.githubusercontent.com/3165635/164559623-ba90f075-6c53-4161-9f0d-071873b3d3f3.png">

- [x] UX: In the binding editor: It would be great for Cmd + S to save in the code editor views or the whole state #254.
- [x] UX: When I'm on the "Create a new MUI Studio Code Component" popup, why is the input already filled with "MyComponent"? If we really want to have a default value, I think that we could have the default value selected so we can more quickly type something new.

<img width="258" alt="Screenshot 2022-04-22 at 00 07 51" src="https://user-images.githubusercontent.com/3165635/164559698-cd4057cf-a506-4660-8cf1-aafa31387eb8.png">

- [x] DX: I wish I had a debugger somewhere to see all my states. I have created a Debugger component to help me. But in the end, I didn't really used it. 

```jsx
import * as React from "react";
import type { ComponentConfig } from "@mui/toolpad-core";

export interface DebugProps {
  msg: string;
  debug: string;
}

export const config: ComponentConfig<DebugProps> = {
  argTypes: {
    msg: {
      typeDef: { type: "object" },
    },
    debug: {
      typeDef: { type: "string" },
    },
  },
};

export default function Debug({ debug = "Debug", msg }: DebugProps) {
  console.log(debug, msg);
  return (
    <div style={{ width: 400, backgroundColor: "red", color: "white" }}>
      Debug
    </div>
  );
}
```

- [x] UX: When I bind a property, I wish I could get a live preview of the new value. Since I don't have this, I press the update binding multiple times. Not great.

<img width="458" alt="Screenshot 2022-04-22 at 00 09 12" src="https://user-images.githubusercontent.com/3165635/164559908-fffdb19a-4f08-4109-a2f9-2d20301bb34f.png">

I even wonder if on hover we shouldn't have a popup to show the content of the variable. So not the type, the value

<img width="471" alt="Screenshot 2022-04-22 at 00 12 10" src="https://user-images.githubusercontent.com/3165635/164560152-20539a7b-9424-40b7-8895-0e7c80b68f45.png">

- [x] DX: I have caught myself forgetting to create a `queryState` multiple times. What could work better is to make what we current call "queryState" an "API" and what we currently call "API" a "Query library". https://github.com/mui/mui-toolpad/issues/365
- [x] UX: Sometimes, I wish I could resize the right-side panel. https://github.com/mui/mui-toolpad/issues/496
- [x] DX: I feel that the JSON type is painful to use. Would it make sense to have a JavaScript object syntax everywhere instead? My main issue is that JSON is less forgiving. You forget a quote, add one more quote and it fails to parse. https://github.com/mui/mui-toolpad/pull/495
- [x] DX: In the "Bind a property" view, it would be interesting to know the nature of the global variable. Is it a component or an API state? It could help more quickly navigate what's available. We might even want to group them. https://github.com/mui/mui-toolpad/issues/497

<img width="195" alt="Screenshot 2022-04-22 at 00 18 49" src="https://user-images.githubusercontent.com/3165635/164560844-e537a607-8409-4c8a-a625-7a6a7ff42089.png">

- [x] DX: I have to handle the case when the data is loading manually. I have disabled the select components. I also had to add defensive logic:

```jsx
getImage?.data?.message
```

- [x] UX: We could have a proper Image component, there is an issue about it on the Material UI repository, maybe to use it as a source of inspiration or even for contribution https://github.com/mui/material-ui/issues/22470

**Comment by Janpot** [comment]
Going to sketch out a rough idea here that is forming around the loading/error states of components. The goal is to wire these up transparently to components that support such states, like the DataGrid

<hr/>

I think we could do the following:

create a marker in the component type definition that designates two special properties:

1. one `boolean` property that represents loading state for the component
2. one `Error` property that represents error state for the component

In the component properties editor it will be possible to wire up whatever logic to these manually in case users want to do their own logic.

**For databinding**

currently, from the code that evaluates binding expression, we already get a two-state as a result

```ts
type LiveBinding = { error: Error } | { value: any };
```

We will add an additional third state

```ts
type LiveBinding = { error: Error } | { value: any } | { loading: boolean };
```

We will then augment the page state that we feed into this evaluator with Proxies that will throw special markers if some property on the state of a datafetch accessed, while it's still loading. The binding evaluator can then catch these markers to know that any of the property accesses is still waiting for something to load. We can then mark the whole expression as loading. The marker will contain a promise that we can wire up for rerendering later on. From a user perspective it will be transparent.

The Toolpad runtime can then wire the result up to the right properties in the component. `value` will go to the property that has been bound, and `loading` and `error` will be filled into the properties designated by the component type definition. (currently all it does is wire up `value` and `error` is only used for debugging)

This way custom components will also be able to designate properties for loading and errors and seamlessly work with Toolpad databinding and datafetching

**Comment by Janpot** [comment]
All issues are either fixed or scoped down to individual github issues
