### ISSUE TITLE
@toolpad/core release plan

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#3892]
## To Do

- [x] verify Toolpad core is still compatible with v5. (Jan) https://github.com/mui/mui-toolpad/pull/3894
- [ ] ...

Toolpad docs PRs to be merged

- [ ] https://github.com/mui/mui-toolpad/pull/3868
- [x] Document that css vars theme is only availbale if you use Material UI v6 https://github.com/mui/mui-toolpad/pull/3894
- [x] https://github.com/mui/mui-toolpad/pull/3864
- [x] https://github.com/mui/mui-toolpad/pull/3848 ✅ 
- [ ] ...

MUI docs PRs to be merged

- [x] https://github.com/mui/material-ui/pull/42952 ✅ 
- [x] https://github.com/mui/material-ui/pull/43036 
- [ ] ...

**Search keywords**:
