### ISSUE TITLE
[EPIC] Duplicate 

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#437]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Make it possible to duplicate everything:

- [x] #843 
- [x] https://github.com/mui/mui-toolpad/issues/1173
- [x] https://github.com/mui/mui-toolpad/issues/1172
- [x] #1036 
- etc.

### Examples 🌈

- Figma:
  - Files:
  <img width="466" alt="Screenshot 2022-05-17 at 15 51 51" src="https://user-images.githubusercontent.com/3165635/168827057-feaf2481-3288-4289-9a95-40ca8f2a6f0d.png">

  - Pages:
  <img width="348" alt="Screenshot 2022-05-17 at 15 48 25" src="https://user-images.githubusercontent.com/3165635/168826300-38fc7cd0-8ef1-4a71-bea3-b32cab3f2866.png">

- VS Code: there the process is a bit different, you copy & paste.

### Motivation 🔦

I would like to split my existing app:

<img width="387" alt="Screenshot 2022-05-17 at 15 53 55" src="https://user-images.githubusercontent.com/3165635/168827507-41ad4177-9778-4c9b-97ea-b90681973d9d.png">

in two: one for experimentations, and one for the support team of MUI X.
