### ISSUE TITLE
In the app view, all pages should also be shown as a list on the left menu bar 

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#813]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When previewing an app that has multiple pages, we can show a toggle asking if the pages should appear in a menu bar on the left. This is how most admin panels look.

We can also ask the developer to set one of the pages as default and show it when the app opens.

This is just one way of implementing it, we can discuss more ways like adding this menu bar as a component. 

### Examples 🌈
<img width="1435" alt="Screenshot 2022-08-17 at 9 04 43 PM" src="https://user-images.githubusercontent.com/92228082/185181366-21cafa39-ffcf-40fa-810a-e07ecd38a7f8.png">

Later on:
1. we can have a header nav bar
2. these 2 components can be prominent in assigning a theme to the app

### Motivation
https://community.retool.com/t/building-side-nav-and-multiple-pages-dashboard/6219

Reference:
https://www.notion.so/mui-org/UI-layout-for-navigation-between-pages-5e69b677da7c4a469205b133c3133fa5

### Benchmark
https://www.npmjs.com/package/react-pro-sidebar

High level tasks

- [x] Add Toolpad shell = navigation sidebar
- [x] Make Toolpad shell removable through query param `?toolpad-display=standalone`
- [x] Remove overview of apps
- [x] initial page (first one for now?)
- [x] preview button directly to the page https://github.com/mui/mui-toolpad/issues/1547

**Comment by Janpot** [comment]
All apps I've seen created so far by internal dogfooding are one page only. Another idea could be to optimize for this use-case and remove the concept of pages altogether. Each app would be just one single page.

We could then later down the road provide multi-page organization with folders in the workspace.

**Comment by prakhargupta1** [comment]
This looks good, much like react admin. We would soon have to conclude how we should show pages, like this way or retool way (page and folders, no concept of app)

**Comment by prakhargupta1** [comment]
I suggest we do it as it will definitely make the app look more complete.  Let me know if there are any objections.
cc: @bharatkashyap

**Comment by bharatkashyap** [comment]
> I suggest we do it as it will definitely make the app look more complete. Let me know if there are any objections. cc: @bharatkashyap

I realised that this creates an issue about authorisation, since now sharing only one page of an app with a user is not possible any more.

**Comment by prakhargupta1** [comment]
Can we not just change this view to the one you showed while keeping everything else same?

<img width="1428" alt="Screenshot 2022-12-21 at 12 53 41 PM" src="https://user-images.githubusercontent.com/92228082/208844998-09470b8c-a115-4cfa-800d-8e3991fa0a85.png">

**Comment by bharatkashyap** [comment]
> Can we not just change this view to the one you showed while keeping everything else same?
> 
> <img width="1428" alt="Screenshot 2022-12-21 at 12 53 41 PM" src="https://user-images.githubusercontent.com/92228082/208844998-09470b8c-a115-4cfa-800d-8e3991fa0a85.png">
> 

The sidebar would show up across all pages, otherwise what would be the point of having a sidebar?

**Comment by prakhargupta1** [comment]
In the deploy pop-up, let's show 2 radio buttons asking how the user wants to deploy the app. 
1) Without a side bar (default)  => It will deploy like we do today.
2) With side bar => It will deploy like we have shown it in the video. For now, let's keep page1 as default.

<img width="680" alt="Screenshot 2023-01-04 at 3 28 24 PM" src="https://user-images.githubusercontent.com/92228082/210530018-80b19323-d4b2-48b7-be16-dee26b33e555.png">

**Comment by Janpot** [comment]
> In the deploy pop-up, let's show 2 radio buttons asking how the user wants to deploy the app.

If we were to add this as an option, I believe it should be configurable separately from the deployment lifecycle. e.g. somewhere under "application options", or maybe even on a per page basis.
<hr>

I'm also wondering: 
* If we were to add this as an option, what would be the function of that overview page that lists all the pages?
* If we're planning on exploring removing multiple pages as a construct, does it still make sense to continue this effort?

**Comment by bharatkashyap** [comment]
> > In the deploy pop-up, let's show 2 radio buttons asking how the user wants to deploy the app.
> 
> If we were to add this as an option, I believe it should be configurable separately from the deployment lifecycle. e.g. somewhere under "application options", or maybe even on a per page basis.

Agreed, I think we must communicate clearly that one option means every page of the app is accessible to everyone with who the app is shared via URL, versus the other option allows sharing only individual pages via URL.

**Comment by prakhargupta1** [comment]
These points make me think that a navigational component like [tabs](https://github.com/mui/mui-toolpad/issues/747) can handle it all, I mean even if we make 1 app=1 page, if someone would want multiple pages on header bar they can use this component. Appsmith deploys like this.

Similarly, if we use [drawer](https://mui.com/material-ui/react-drawer/) component, user would be able to have multiple pages on the left bar.

**Comment by prakhargupta1** [comment]
As discussed [here](https://www.notion.so/mui-org/Planning-W54-251ebd5015cf48c088d9aff969a9367a#adb57edb053f4f5b9a11ae59d58d3fee) we decided to show a deployed app with all pages listed on a left drawer.  And that there will be default a page.

This will:
a.) Break the Zendesk iframe app or the apps that we have embedded in notion. Though we discussed that a single page can be made accessible (like we do today) through query parameters.
b.) Not go with direction 13 as a Toolpad page will be a react component there and the way to arrange all pages as apps is unclear. 

So, maybe it makes sense to not take this forward till we get further clarity.

**Comment by Janpot** [comment]
@prakhargupta1 I'm not sure I follow, didn't we decide to add a drawer to the left:

* Containing a navigation UI for all the pages within the app
* Add an option that denotes a "home page" to be initially opened when navigating to the root of the app
* Removing the overview page, solving: https://github.com/mui/mui-toolpad/issues/1547
* Add an option to the app to disable this UI for the zendesk use-case

**Comment by prakhargupta1** [comment]
Yes we did. Cool, let's take it forward then. Just reiterating how I understood it:

- the navigation UI will be there by default, even if it is a single page app. 
- If there are 2 or more pages, then one of them will be default and it will be possible to change it from the page menu.
- It will be applicable both for preview and deploy view.
- When previewing the page separately from the right sidebar, it won't come with the navigation UI.
- About how to disable this UI, I think it applies only to our internal apps, so controlling it through a query parameter should be sufficient.

**Comment by prakhargupta1** [comment]
Retool has also started supporting sidebar navigation (in addition to header navigation). Example [app](https://mui.retool.com/apps/23d94e94-9631-11ed-8da8-1322da1a9047/Chart_app?_releaseVersion=latest)

**Comment by bharatkashyap** [comment]
> * When previewing the page separately from the right sidebar, it won't come with the navigation UI.

What does this mean?

**Comment by prakhargupta1** [comment]
> What does this mean?

That we'll show page preview (like we show today) when previewing it from here: 
<img width="294" alt="Screenshot 2023-01-31 at 11 20 32 AM" src="https://user-images.githubusercontent.com/92228082/215677420-29290df4-0f21-41b5-b87e-1d642ba5e86a.png">
